
package es.uniovi.miw.ws.unit04.example1.webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CalculatorWS", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.AddResponse")
    @Action(input = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/addRequest", output = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.SubResponse")
    @Action(input = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/subRequest", output = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/subResponse")
    public double sub(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.MulResponse")
    @Action(input = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/mulRequest", output = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/mulResponse")
    public double mul(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     * @throws DividedByZeroException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.unit04.example1.webservices.DivResponse")
    @Action(input = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/divRequest", output = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/divResponse", fault = {
        @FaultAction(className = DividedByZeroException_Exception.class, value = "http://webservices.example1.unit03.ws.miw.uniovi.es/CalculatorWS/div/Fault/DividedByZeroException")
    })
    public double div(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws DividedByZeroException_Exception
    ;

}
