
package es.uniovi.miw.ws.unit04.example1.webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "DividedByZeroException", targetNamespace = "http://webservices.example1.unit03.ws.miw.uniovi.es/")
public class DividedByZeroException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DividedByZeroException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DividedByZeroException_Exception(String message, DividedByZeroException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DividedByZeroException_Exception(String message, DividedByZeroException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.uniovi.miw.ws.unit04.example1.webservices.DividedByZeroException
     */
    public DividedByZeroException getFaultInfo() {
        return faultInfo;
    }

}
